### ISSUE TITLE
RBF Kernel Calculation Skips Contribution from Omitted Data Points

### ISSUE THREAD

**Issue by timkaas** [ralfbiedert/ffsvm#12]
When dealing with omitted data points, an addition to the sum is completely skipped, despite a feature or sv value being zero, the other can still contribute to the calculated kernel value.

Inspecting your rbf-implementation, you want to change it to:
```rust
output[i] = loop {
                match (a, b) {
                    (Some((i_a, x)), Some((i_b, y))) if i_a == i_b => {
                        sum += (x - y) * (x - y);

                        a = a_iter.next();
                        b = b_iter.next();
                    }
                    (Some((i_a, x)), Some((i_b, _))) if i_a < i_b => {
                        a = a_iter.next(); sum += x*x;
                    },
                    (Some((i_a, _)), Some((i_b, y))) if i_a > i_b => {
                        b = b_iter.next(); sum += y*y
                    },
                    _ => break f64::from((-self.gamma * sum).exp()),
                }
```
note here the accumulation of `x*x` and `y*y` when the opposite is not present.

**Comment by ralfbiedert** [comment]
Thanks for the report! I'd be happy to accept a PR for that (preferably including a unit test against libsvm results).

**Comment by timkaas** [comment]
Made a pull request that implements above fixes. Let me know if further action is required from my side. Please note, this is my first PR, so bear with me should i have forgotten/messed up something.

**Comment by ralfbiedert** [comment]
Sorry, I thought I merged that already, thanks a lot!
